#!/bin/bash
# Quick Reference for Stripe Payment Testing

echo "=== Stripe Payment Integration Testing Guide ==="
echo ""
echo "1. START DEV SERVER"
echo "   cd /Users/abdelrahmanali/Downloads/Blue-Design/angular-last-last-blue-2"
echo "   npm run start -- --host 0.0.0.0 --port 4200"
echo ""
echo "2. START NGROK TUNNEL (in another terminal)"
echo "   ngrok http 4200"
echo "   Note the forwarding URL (e.g., https://xxx-xxx-xxx.ngrok-free.dev)"
echo ""
echo "3. UPDATE BACKEND"
echo "   - Set webhook URL to: {ngrok-url}/api/payment/stripe/webhook"
echo "   - Verify Stripe API key is configured"
echo ""
echo "4. TEST PAYMENT FLOW"
echo "   - Navigate to: http://localhost:4200/plans"
echo "   - Login if needed"
echo "   - Click 'Try Now' on any plan"
echo "   - Use test card: 4242 4242 4242 4242"
echo "   - Expiry: 12/34, CVC: 123"
echo "   - Complete payment"
echo "   - Verify redirect to success page"
echo ""
echo "5. CHECK BROWSER CONSOLE"
echo "   Look for logs with these prefixes:"
echo "   - [PlansPage]"
echo "   - [PaymentSuccess]"
echo "   - [PaymentService]"
echo ""
echo "6. VERIFY PAYMENT"
echo "   - Success page should auto-verify payment"
echo "   - Should show transaction ID and details"
echo "   - Should have buttons: 'Go to Dashboard' and 'View Plans'"
echo ""
echo "7. TEST CANCEL"
echo "   - Click 'Try Now' again"
echo "   - Click back/close on Stripe checkout"
echo "   - Should redirect to cancel page"
echo "   - Should show 'Payment Cancelled' message"
echo ""
echo "=== Test Cards ==="
echo ""
echo "Successful Payment:"
echo "  Number: 4242 4242 4242 4242"
echo "  Expiry: 12/34 (any future date)"
echo "  CVC: 123 (any 3 digits)"
echo ""
echo "Card Declined:"
echo "  Number: 4000 0000 0000 0002"
echo ""
echo "=== Useful Commands ==="
echo ""
echo "Kill port 4200:"
echo "  lsof -ti :4200 | xargs kill -9"
echo ""
echo "View payment transaction in sessionStorage:"
echo "  // In browser console:"
echo "  JSON.parse(sessionStorage.getItem('payment_transaction'))"
echo ""
echo "Test verify endpoint (after successful payment):"
echo "  curl -X POST http://localhost:5164/api/payment/verify \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"session_id\": \"SESSION_ID_HERE\"}'"
echo ""
echo "=== File Changes ==="
echo ""
echo "✓ src/app/components/plans-page/plans-page.component.ts"
echo "  - Success URL: /paymob/response"
echo "  - Cancel URL: /paymob/cancel"
echo ""
echo "✓ src/app/app.routes.ts"
echo "  - Added: { path: 'paymob/response', component: PaymentSuccessComponent }"
echo "  - Added: { path: 'paymob/cancel', component: PaymentCancelComponent }"
echo ""
echo "✓ src/app/components/payment-success/payment-success.component.ts"
echo "  - Handles Stripe session_id query parameter"
echo "  - Auto-verifies payment"
echo "  - Shows transaction details"
echo ""
echo "✓ src/app/components/payment-cancel/payment-cancel.component.html"
echo "  - Improved UI for cancel flow"
echo ""
echo "✓ src/app/services/payment.service.ts"
echo "  - Enhanced verify() to handle session_id"
echo ""
